language: java

services:
  - postgresql
addons:
  postgresql: "9.5"
  sonarcloud:
    organization: "napstr-github"

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - TEST_DB_JDBC: "jdbc:postgresql://localhost:5432/testing?user=postgres"
    - BINTRAY_USER: napster
    - secure: "fGaTKEocR9W0FLnJfU3i0oGVVJwsOzllm/wA+zb1bxqCeMT/mk3rK0bSJBF4KizAqZJfUoUSV+kIpxHnMma7lbc+Aez0LwkleCIpkXmC07Odm8wo6sN8Q3cTR083K6sFohG3TxeZBwygbkWbSsIYJTZhyLb3S7ZDuRWuFlQwy88akou3z6nFzBezHtU8DmljH/ut2JpX2TECsHS080HfQUqOjHqY/ms+Jvok3hZZXC0vdOx/P9xmmWCNXIpLbHhIAbReu2Xm/e2E/AxjiPa0nAngu0qWjzve0ls8vTcOyc9nozVqfdQ6+n0oxlM49mzjhs/DHaHsuqUOVGtQ94GIssbyCjwd9iCHsgFinOYrrV3+qoqNAwnVb91j9Z8KHHVrCJUZLLhR0CKZnWhVNaYz4JbCOL3ANKIoXyKZ5Xh+qrjGRD/NefuYZUS2eijERoFDnm5tDVdK2Lyz9YMjGvFZsedG/gmy7vIHFWTEy70RYwgziCbD7qSDyXetDN7cwqexDrsklua/31wg26GiVQCqVPzV1DcrI3fBujKLB306mNEydxVGUWR8OKIweIo3KE8SJEPUKmDGEUN8yJzT/kgavnfBX0ymn1kkYzZEvxEKqpJ85Aiw+d8TCxAk6HmqTtu56cOIkkXRTI/XDttdoJ2B0eAHJxSreIkR43VMAjwJJOM="

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - build & test
  - sonar
  - name: publish
    if: tag IS present

jobs:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
    - jdk: oraclejdk-ea
  include:
    - stage: build & test
      jdk: openjdk8
      before_script:
        - "psql -c 'create database testing;' -U postgres"
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: oraclejdk8
      before_script:
        - "psql -c 'create database testing;' -U postgres"
      script:
        - "java -Xmx32m -version"
        - "./gradlew build --info"

    - stage: build & test
      jdk: openjdk-ea
      before_script:
        - "psql -c 'create database testing;' -U postgres"
      script:
        - "java -Xmx32m -version"
        - "./gradlew build -x test --info" #tests skipped due to jacoco incompatibility, watch https://github.com/jacoco/jacoco/issues/663

    - stage: build & test
      jdk: oraclejdk-ea
      before_script:
        - "psql -c 'create database testing;' -U postgres"
      script:
        - "java -Xmx32m -version"
        - "./gradlew build -x test --info" #tests skipped due to jacoco incompatibility, watch https://github.com/jacoco/jacoco/issues/663

    - stage: sonar
      jdk: openjdk8
      before_script:
        - "psql -c 'create database testing;' -U postgres"
        #for sonar cloud blame information
        - "git fetch --unshallow"
      script:
        - "java -Xmx32m -version"
        - "./gradlew sonarqube"

    - stage: publish
      jdk: openjdk8
      script:
        - "java -Xmx32m -version"
        - "./gradlew pub"
